// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjIz8bPy749CX6OgKuFoUHX2pZTbiZtwg',
    appId: '1:923588403397:web:7e42599ecd92d93b98d0ac',
    messagingSenderId: '923588403397',
    projectId: 'crud-teste-flutter',
    authDomain: 'crud-teste-flutter.firebaseapp.com',
    databaseURL: 'https://crud-teste-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'crud-teste-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHY-hiASTzTodzzHca1kiWMKZtmaUKupQ',
    appId: '1:923588403397:android:f974d43f5f8b052398d0ac',
    messagingSenderId: '923588403397',
    projectId: 'crud-teste-flutter',
    databaseURL: 'https://crud-teste-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'crud-teste-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06DYTPfPjT6bDIRiw81r6hsKLU0bljBo',
    appId: '1:923588403397:ios:7ff30ccd2b40092b98d0ac',
    messagingSenderId: '923588403397',
    projectId: 'crud-teste-flutter',
    databaseURL: 'https://crud-teste-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'crud-teste-flutter.appspot.com',
    iosClientId: '923588403397-m6khrerlh0klgc1tfu7tct661281h159.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbTeste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA06DYTPfPjT6bDIRiw81r6hsKLU0bljBo',
    appId: '1:923588403397:ios:7ff30ccd2b40092b98d0ac',
    messagingSenderId: '923588403397',
    projectId: 'crud-teste-flutter',
    databaseURL: 'https://crud-teste-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'crud-teste-flutter.appspot.com',
    iosClientId: '923588403397-m6khrerlh0klgc1tfu7tct661281h159.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbTeste',
  );
}
